export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETALS_REQUEST = 'PRODUCT_DETALS_REQUEST';
export const PRODUCT_DETALS_SUCCESS = 'PRODUCT_DETALS_SUCCESS';
export const PRODUCT_DETALS_FAIL = 'PRODUCT_DETALS_FAIL';
